//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.CompraProveedor = new HashSet<CompraProveedor>();
        }
    
        public int idProveedor { get; set; }
        public string nombreProveedor { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string estadoProveedor { get; set; }
        public int idDireccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraProveedor> CompraProveedor { get; set; }
        public virtual Direccion Direccion { get; set; }
    }
}
